[mgr]
linemode = "mtime"
# show_hidden = true
show_symlink = true

[opener]
edit = [
	{ run = 'nvim %s', block = true, for = "unix" },
]

imv = [
	{ run = 'imv-dir %s1', orphan = true, desc = "imv-dir", for = "linux" },
]

mpv = [
	{ run = 'mpv %s', orphan = true, desc = "mpv", for = "unix" },
]

[open]
prepend_rules = [
	{ mime = "image/*", use = "imv" },
	{ mime = "audio/*", use = "mpv" },
	{ mime = "video/*", use = "mpv" },
]
