[mgr]
linemode = "mtime"
# show_hidden = true
show_symlink = true

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
	{ run = "nvim %*",  block = true, for = "windows" },
]

imv = [
	{ run = 'imv-dir "$1"', orphan = true, desc = "imv-dir", for = "linux" },
]

mpv = [
	{ run = 'mpv "$@"', orphan = true, desc = "mpv", for = "unix" },
]

[open]
prepend_rules = [
	{ mime = "image/*", use = "imv" },
	{ mime = "video/*", use = "mpv" },
]
